<div class="ui grid">
    <div class="twelve wide column">
        delete
    </div>
</div>

<div class="four wide column">

    <div class="ui vertical menu">
        <div class="header item"><a href="/listing/index">Pregled ponude</a></div>
        <a href="/user" class="item">Moj Račun</a>
        <a class="item" href="/user/change-email">Promijeni email</a>
        <a class="item" href="/user/change-password">Promijeni Lozinku</a>
        <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
    </div>

</div>
</div>
