<div class="ui grid">
    <div class="twelve wide column">
        <h1>Uredi ponudu</h1>
        <div class="ui large form" _lpchecked="1">
            <form method="post" action="/listing/editSave/<?php echo $listing->getId(); ?>" enctype="multipart/form-data">

                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            <input value="<?php echo $listing->getName(); ?>" id="edit-name" placeholder="Ime ponude" type="text" name="name"/>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="phone icon"></i>
                            <input value="<?php echo $listing->getDescription(); ?>" id="edit-description" placeholder="Opis ponude" type="text" name="description" />
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="map icon"></i>
                            <input value="<?php echo sprintf("%.2f", $listing->getPrice()); ?>" id="edit-price" type="text" placeholder="Cijena" name="price" />
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui left icon input">
                            <i class="image icon"></i>
                            <input id="edit-image" type="file" placeholder="Slika" name="image" />
                        </div>
                    </div>

                    <button type="submit" value="Spremi" class="ui fluid large submit button">Spremi</button>
                </div>
            </form>
        </div>
    </div>

    <div class="four wide column">
        <div class="ui vertical menu">
            <div class="item">
                <span class="ui circular image">
                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
                </span>
                <strong><?php echo $this->zfcUserDisplayName();?></strong>
            </div>
            <a class="item" href="/user">Moj Račun</a>
            <a class="item" href="/listing/index">Pregled ponude</a>
            <a class="item" href="/user/change-email">Promijeni email</a>
            <a class="item" href="/user/change-password">Promijeni Lozinku</a>
            <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
        </div>
    </div>
</div>
