<div class="ui divided items">
    <div class="item">
        <div class="image">
            <img src="http://placehold.it/200x200">
        </div>
        <div class="content">
            <a class="header"><?php echo $this->zfcUserIdentity()->getDisplayName(); ?></a>
            <div class="meta">
                <span class="cinema"><?php echo $this->zfcUserIdentity()->getAddress(); ?></span>
            </div>
            <div class="description">
                <p><?php echo $this->zfcUserIdentity()->getDescription(); ?></p>
            </div>
            <div class="extra">
                <div class="ui label green"><i class="checkmark box icon"></i> Provjeren</div>
            </div>
        </div>
    </div>
</div>

<?php foreach ($this->listings as $k => $listing) : ?>
<?php if ($k % 3 === 0 && $k > 0) : ?>
    </div>
    <?php endif; ?>
<?php if ($k % 3 === 0) : ?>
<div class="ui three column grid stackable">
    <?php endif;?>
    <div class="column">
        <div class="ui fluid card">
            <div class="image">
                <img src="http://placehold.it/200x200">
            </div>
            <div class="content">
                <a class="header"><?php echo $listing->getName(); ?></a>
                <div class="description">
                    <?php echo $listing->getDescription(); ?>
                </div>
            </div>
            <div class="extra content">
                <a href="/listing/<?php echo $listing->getUserId(); ?>">
                    <i class="user icon"></i>
                    <?php echo $this->providersMap[$listing->getUserId()]->getDisplayName(); ?>
                </a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
    <?php //if ($k % 3 !== 0) : ?>
    <!--    </div>-->
    <?php //endif; ?>
</div>
