
<?php if (!$this->zfcUserIdentity()):?>
    <div class="ui horizontal divider">
        Postani dobavljač!
    </div>

    <div class="ui steps tablet stackable">
    <div class="step">
        <i class="user icon"></i>
        <div class="content">
            <div class="title"><a href="">Registriraj Se:</a></div>
            <div class="description">Iskoristi priliku da dosegneš kupce koji žele tvoj proizvod</div>
        </div>
    </div>
    <div class="step">
        <i class="gift icon"></i>
        <div class="content">
            <div class="title">Katalog</div>
            <div class="description">Postavi proizvode na  našu stranicu</div>
        </div>
    </div>
    <div class="step">
        <i class="truck icon"></i>
        <div class="content">
            <div class="title">Isporuči robu na pravu adresu</div>
            <div class="description">Ili dopusti kupcu da ju sam preuzme...</div>
        </div>
    </div>
</div>
<div class="ui horizontal divider">
    Paketi Svježe Hrane
</div>
<?php endif; ?>

<a href="/listing/add" class="ui large submit button orange">Dodaj novu ponudu</a><br/><br/>
<div class="ui grid stackable">
    <div class="twelve wide column">

    <?php foreach ($this->listings as $k => $listing) : ?>
        <?php if ($k % 3 === 0 && $k > 0) : ?>
        </div>
        <?php endif; ?>
        <?php if ($k % 3 === 0) : ?>
        <div class="ui three column grid stackable">
        <?php endif;?>
            <div class="column">
                <div class="ui fluid card">
                    <div class="image">
                        <?php if ($listing->getImageLink()):?>
                            <img src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/cdn/uploads/' . $listing->getImageLink() ?>">
                        <?php else: ?>
                            <img src="http://placehold.it/200x200">
                        <?php endif;?>
                    </div>
                    <div class="content">
                        <a class="header"><?php echo $listing->getName(); ?></a>
                        <div class="description">
                            <?php echo $listing->getDescription(); ?>
                        </div>
                        <div class="price">
                            <?php echo sprintf("%.2f", $listing->getPrice()); ?> KN
                        </div>
                    </div>
                    <div class="extra content">
                        <a href="/listing/delete/<?php echo $listing->getId()?>">Briši ponudu</a> |
                        <a href="/listing/edit/<?php echo $listing->getId()?>">Uredi ponudu</a>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

        </div>
<div class="four wide column">
    <div class="ui vertical menu">
        <div class="item">Moj Račun</div>
        <div class="item">
                <span class="ui circular image">
                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
                </span>
            <strong><?php echo $this->zfcUserDisplayName();?></strong>
        </div>
        <a class="item" href="/user">Moj Podaci</a>
        <a class="item" href="/listing/index">Pregled ponude</a>
        <a class="item" href="/user/change-email">Promijeni email</a>
        <a class="item" href="/user/change-password">Promijeni Lozinku</a>
        <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
    </div>
</div>




