<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('OPG'. $this->translate(' - Zippo'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <script src="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/components/reset.min.css">
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.css">
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/components/site.min.css">


        <style type="text/css">
            .site-container{
                padding: 1em 0;
            }


        </style>

    </head>
    <body>
        <div class="ui main container site-container">
            <div class="ui stackable menu">
                <div class="item">
                    <h1><a href="<?php echo $this->url("application"); ?>">ORGAN&KA</a></h1>
                </div>
                <a class="item">Features</a>
                <a class="item">Testimonials</a>

                <div class="right menu">
                    <?php if ($this->zfcUserIdentity()):?>
                    <a class="item" href="/user"><i class="sign in icon"></i>
                    <?php echo $this->zfcUserIdentity()->getEmail();?>
                    </a>
                    <a class="item"><i class="in cart icon"></i> Košarica</a>
                    <?php else: ?>
                        <a class="item" href="/user/login"><i class="sign in icon"></i> Moj račun</a>
                        <a class="item"><i class="in cart icon"></i> Košarica</a>
                    <?php endif;?>


                </div>
            </div>
            
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
