<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Farma Direkt')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <script src="//code.jquery.com/jquery-2.1.4.js"></script>
        <script src="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.css">



        <style type="text/css">
            body{
                background: url(http://subtlepatterns2015.subtlepatterns.netdna-cdn.com/patterns/symphony.png);
            }
            .site-container{
                padding: 1em 0;
            }
            .site-logo{
                text-align: center;

            }
            .site-logo img{
                padding-top: 0.5em;
                width: 100%;
                max-width: 150px;
            }
            .ui.vertical.segment.site-footer{
                margin-top: 3em;
                padding-top: 1em;
                background: #fff;

            }
            .description{
                width: 100%;

                overflow: hidden;
                max-height: 60px;
                margin-bottom: 0.5em;
            }
            .ui.vertical.menu{
                width: 100%;
            }
            .ui.vertical.menu>.item:first-child{
                font-weight: 600;
                background-color: #f9f9f9;
            }
            .ui.stacked.segment label{
                display: block;
                clear: both;
                width: 30%;
                font-weight: 600;
            }
            .alert.alert-error{
                position: relative;
                min-height: 1em;
                margin: 1em 0;
                padding: 1em 1.5em;
                line-height: 1.4285em;
                color: rgba(0, 0, 0, .87);
                -webkit-transition: opacity .1s ease, color .1s ease, background .1s ease, box-shadow .1s ease;
                transition: opacity .1s ease, color .1s ease, background .1s ease, box-shadow .1s ease;
                border-radius: .28571429rem;
                background-color: #fff6f6;
                color: #9f3a38;
                box-shadow: 0 0 0 1px #e0b4b4 inset, 0 0 0 0 transparent
            }
            .price{
                font-weight: 600;
            }
        </style>

    </head>
    <body>
        <div class="ui main container site-container">
            <div class="ui grid stackable">
                <h1 class="site-logo three wide column">
                    <a href="<?php echo $this->url("application"); ?>">
                        <img src="/cdn/assets/images/farma-direkt-logo.png" alt="">
                    </a>
                </h1>
                <div class="thirteen wide column">

                    <div class="ui secondary menu">
                        <a class="active item" href="<?php echo $this->url("application"); ?>">
                            Početna
                        </a>
                        <div class="menu right">
                                <?php if ($this->zfcUserIdentity()):?>
                                    <div class="item">
                                        <a class="ui button" href="/user"><i class="sign in icon"></i>
                                            <?php echo $this->zfcUserIdentity()->getEmail();?>
                                        </a>
                                    </div>
                                <?php else: ?>
                                    <div class="item">
                                        <a class="ui button" href="/user/login"><i class="sign in icon"></i>
                                            Moj Račun
                                        </a>
                                    </div>
                                <?php endif;?>
                        </div>
                    </div>


                <div class="ui menu">
                    <div class="item">
                        <strong>
                            Voće i povrće pred Vaša vrata.
                        </strong>
                    </div>
                    <div class="compact menu right">
                            <div class="item">
                                <a class="ui button green" href="/order/index"><i class="in cart icon"></i> Košarica</a>
                            </div>
                    </div>
                </div>

                </div>
            </div>

            <?php echo $this->content; ?>
        </div>
        <div class="ui vertical footer segment site-footer">
            <div class="ui container">
                <div class="ui stackable divided equal height stackable grid">
                    <div class="sixteen wide column">
                        <h4 class="ui header">Team Zippo</h4>
                        <p>Made na katu | 2015</p>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
