<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FarmaDirekt')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <script src="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.js"></script>
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/components/reset.min.css">
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/semantic.min.css">
        <link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.4/components/site.min.css">


        <style type="text/css">
            .site-container{
                padding: 1em 0;
            }
            .site-logo img{
                width: 100%;
                max-width: 150px;
            }
            .description{
                width: 100%;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
            }
            .ui.vertical.menu{
                width: 100%;
            }
            .ui.vertical.menu>.item:first-child{
                font-weight: 600;
                background-color: #f9f9f9;
            }
            .ui.stacked.segment label{
                display: block;
                clear: both;
                width: 30%;
                font-weight: 600;
            }
            .alert.alert-error{
                position: relative;
                min-height: 1em;
                margin: 1em 0;
                padding: 1em 1.5em;
                line-height: 1.4285em;
                color: rgba(0, 0, 0, .87);
                -webkit-transition: opacity .1s ease, color .1s ease, background .1s ease, box-shadow .1s ease;
                transition: opacity .1s ease, color .1s ease, background .1s ease, box-shadow .1s ease;
                border-radius: .28571429rem;
                background-color: #fff6f6;
                color: #9f3a38;
                box-shadow: 0 0 0 1px #e0b4b4 inset, 0 0 0 0 transparent
            }
        </style>

    </head>
    <body>
        <div class="ui main container site-container">
            <h1 class="site-logo">
                <a href="<?php echo $this->url("application"); ?>">
                    <img src="/cdn/assets/images/farma-direkt-logo.png" alt="">
                </a>
            </h1>

            <div class="ui stackable menu">
                <a class="item"><strong>Domaće je najbliže</strong></a>
<!--                <a class="item">Features</a>-->
<!--                <a class="item">Testimonials</a>-->
                <div class="right menu">
                    <?php if ($this->zfcUserIdentity()):?>
                    <a class="item" href="/user"><i class="sign in icon"></i>
                    <?php echo $this->zfcUserIdentity()->getEmail();?>
                    </a>
                    <a class="item"><i class="in cart icon"></i> Košarica</a>
                    <?php else: ?>
                        <a class="item" href="/user/login"><i class="sign in icon"></i> Moj račun</a>
                        <a class="item"><i class="in cart icon"></i> Košarica</a>
                    <?php endif;?>


                </div>
            </div>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
