<div class="ui divided items">
    <div class="item">
        <div class="image">
            <img src="http://placehold.it/200x200">
        </div>
        <div class="content">
            <a class="header">OPG ZLATKOV - TRAMONTANA WOOD CRAFT OTOK CRES</a>
            <div class="meta">
                <span class="cinema">Filozići 9, 51574 Cres | Kvarner</span>
            </div>
            <div class="description">
                <p>Opg Zlatkov - Tramontana wood craft nalazi se na otoku Cresu u malom mjestu Filozići koje ima svega tridesetak, većinom nenastanjenih kuća, i samo tri obitelji koje borave tokom cijele godine, ali zato ništa manje vrijednim posjeta!</p>
            </div>
            <div class="extra">
                <div class="ui right floated primary button">
                    Ponuda
                    <i class="right chevron icon"></i>
                </div>
                <div class="ui label green"><i class="checkmark box icon"></i> Provjeren</div>

            </div>
        </div>
    </div>
</div>