<?php foreach ($this->listings as $k => $listing) : ?>
<?php if ($k % 3 === 0 && $k > 0) : ?>
    </div>
    <?php endif; ?>
<?php if ($k % 3 === 0) : ?>
<div class="ui three column grid stackable">
    <?php endif;?>
    <div class="column">
        <div class="ui fluid card">
            <div class="image">
                <?php if ($listing->getImageLink()):?>
                    <img src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/cdn/uploads/' . $listing->getImageLink() ?>">
                <?php else: ?>
                    <img src="http://placehold.it/200x200">
                <?php endif;?>
            </div>
            <div class="content">
                <a class="header"><?php echo $listing->getName(); ?></a>
                <div class="description">
                    <?php echo $listing->getDescription(); ?>
                </div>
                <div class="price">
                    <?php echo sprintf("%.2f", $listing->getPrice()); ?> KN
                </div>
            </div>
            <div class="extra content">
                <a href="/order/add/<?php echo $listing->getId(); ?>" class="ui button orange">Naruči</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
