<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>


<div class="ui grid">
    <div class="twelve wide column">
        <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
        <h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
        <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
        <div style="clear:both;"></div>

        <dl class="zend_form">
            <?php echo $this->formElementErrors($form->get('identity')); ?>
            <dd><?php echo $this->formInput($form->get('identity')); ?></dd>

            <dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
            <dd><?php
                echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
                ?></dd>

            <dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
            <dd><?php
                echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
                ?></dd>

            <dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
            <dd><?php
                echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
                ?></dd>

            <dd><?php
                //echo $this->formInput($form->get('csrf'));
                echo $this->formInput($form->get('submit'));
                ?></dd>

        </dl>

        <?php echo $this->form()->closeTag(); ?>




    </div>
    <div class="four wide column">
        <div class="ui vertical menu">
            <div class="item">
                <span class="ui circular image">
                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
                </span>
                <strong><?php echo $this->zfcUserDisplayName();?></strong>
            </div>
            <a class="item" href="/user">Moj Račun</a>
            <a class="item" href="/listing/index">Pregled ponude</a>
            <a class="item" href="/user/change-email">Promijeni email</a>
            <a class="item" href="/user/change-password">Promijeni Lozinku</a>
            <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
        </div>
    </div>
</div>













