<?php if ($status === true) : ?>
<div class="alert alert-success"><?php echo $this->translate('Password changed successfully.');?></div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>


<div class="ui grid">
    <div class="twelve wide column">
        <h1>Promijeni Lozinku</h1>
        <div class="ui large form" _lpchecked="1">
        <div class="ui stacked segment">

                <?php echo $this->formElementErrors($form->get('identity')->setAttribute('class', 'ui negative message')); ?>
                        <?php echo $this->formInput($form->get('identity')); ?>

                <div class="field">
                    <div class="ui left input">
                        <?php echo $this->formLabel($form->get('credential')); ?>
                        <?php echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential')); ?>
                    </div>
                </div>
            <div class="field">
                <div class="ui left input">
                    <?php echo $this->formLabel($form->get('newCredential')); ?>
                    <?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?>
                </div>
            </div>

            <div class="field">
                <div class="ui left input">
                    <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
                    <?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')); ?>
                </div>
            </div>

                <?php echo $this->formInput($form->get('submit')->setAttribute('class', 'ui submit button fluid large')); ?>

        <?php echo $this->form()->closeTag(); ?>
        </div>
        </div>


    </div>
    <div class="four wide column">
        <div class="ui vertical menu">
            <div class="item">Moj Račun</div>
            <div class="item">
                <span class="ui circular image">
                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()); ?>
                </span>
                <strong><?php echo $this->zfcUserDisplayName();?></strong>
            </div>
            <a class="item" href="/user">Moj Podaci</a>
            <a class="item" href="/listing/index">Pregled ponude</a>
            <a class="item" href="/user/change-email">Promijeni email</a>
            <a class="item" href="/user/change-password">Promijeni Lozinku</a>
            <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
        </div>
    </div>
</div>













