
<div class="ui grid">
    <div class="twelve wide column">
        <h1>Moji podaci</h1>
        <h2 class="ui header">
            <div class="ui circular image">
                <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
            </div>

            <?php echo $this->zfcUserDisplayName() ?>
        </h2>
    </div>
    <div class="four wide column">

    <div class="ui vertical menu">
        <div class="header item"><a href="/user">Moj Račun</a> </div>
        <a class="item" href="/user/change-email">Promijeni email</a>
        <a class="item" href="/user/change-password">Promijeni Lozinku</a>
        <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
    </div>

    </div>
</div>
