
<div class="ui grid">
    <div class="twelve wide column">
        <h1>Moji podaci</h1>
        <h2 class="ui header">
            <div class="ui circular image">
                <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
            </div>

            <?php echo $this->zfcUserDisplayName() ?>

            <form method="post" action="/account/edit">
                <label for="edit-name">Ime</label><br/>
                <input id="edit-name" type="text" name="name" value="<?php echo $this->zfcUserIdentity()->getDisplayName() ?>" /><br/>
                <label for="edit-phone">Broj telefona</label><br/>
                <input id="edit-phone" type="text" name="phone" value="<?php echo $this->zfcUserIdentity()->getPhone() ?>" /><br/>
                <label for="edit-address">Adresa</label><br/>
                <input id="edit-phone" type="text" name="address" value="<?php echo $this->zfcUserIdentity()->getAddress() ?>" /><br/>
                <label for="edit-description">Opis</label><br/>
                <textarea id="edit-description" name="description"><?php echo $this->zfcUserIdentity()->getDescription() ?></textarea><br/>
                <input type="submit" value="Spremi"/>
            </form>
        </h2>
    </div>
    <div class="four wide column">

    <div class="ui vertical menu">
        <div class="header item"><a href="/user">Moj Račun</a> </div>
        <a class="item" href="/user/change-email">Promijeni email</a>
        <a class="item" href="/user/change-password">Promijeni Lozinku</a>
        <a class="item" href="<?php echo $this->url('zfcuser/logout') ?>"><strong><?php echo $this->translate('Odjava'); ?></strong></a>
    </div>

    </div>
</div>
