<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login', array('redirect' => '/')));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui image header">
            <div class="content">
                Prijava
            </div>
        </h2>
        <div class="ui large form" _lpchecked="1">
        <?php echo $this->form()->openTag($form) ?>
        <?php echo $this->formElementErrors($form->get('identity')) ?>
            <div class="ui stacked segment">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <?php echo $this->formInput($form->get('identity')) ?>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <?php echo $this->formInput($form->get('credential')) ?>
                    </div>
                </div>
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'ui fluid large submit button')) ?>
            </div>
            <div class="ui error message">hello</div>
            <?php echo $this->form()->closeTag() ?>
        </div>

        <div class="ui message">
            New to us?
            <?php if ($this->enableRegistration) : ?>
                <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
            <?php endif; ?>
        </div>
    </div>
</div>


