<h1><?php echo $this->translate('Ono s lozinkom'); ?></h1>

<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'), array('redirect' => '/'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<div class="ui large form" _lpchecked="1">
    <div class="ui stacked segment">
        <?php echo $this->form()->openTag($form) ?>

            <?php foreach ($form as $element): ?>
                <div class="field">
                    <div class="ui left input">
                <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                    <?php echo $this->formLabel($element) ?>
                <?php endif ?>
                <?php if ($element instanceof Zend\Form\Element\Button): ?>
                    <?php echo $this->formButton($element->setAttribute('class', 'ui fluid large submit button')) ?>
                <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                    <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
                <?php else: ?>
                    <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
                <?php endif ?>
                    </div>
                </div>
            <?php endforeach ?>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>