<h1>Košarica</h1>

<table class="ui celled padded table">
    <thead>
    <tr><th class="single line">Slika proizvoda</th>
        <th>Naziv proizvoda</th>
        <th>Opis</th>
        <th>Količina</th>
        <th>Uredi</th>
    </tr></thead>
    <tbody>
    <?php foreach ($this->listings as $k => $listing) : ?>
        <tr>
            <td>
                <h2 class="ui center aligned header">
                    <div class="image">
                        <?php if ($listing->getImageLink()):?>
                            <img width="60" height="60" src="<?php echo 'http://' . $_SERVER['HTTP_HOST'] . '/cdn/uploads/' . $listing->getImageLink() ?>">
                        <?php else: ?>
                            <img src="http://placehold.it/60x60">
                        <?php endif;?>
                    </div>
                </h2>
            </td>
            <td class="single line">
                <?php echo $listing->getName(); ?>
            </td>
            <td>
                <?php echo $listing->getDescription(); ?>
            </td>
            <td class="right aligned">
                <?php echo $this->qty[$listing->getId()]; ?>
            </td>
            <td><a href="/order/remove/<?php echo $listing->getId(); ?>">x</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="ui large form" _lpchecked="1">
    <form method="post" action="/account/edit">
        <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input id="" type="text" name="name" value="" placeholder="Ime i Prezime"/>
                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="mail icon"></i>
                    <input id="" type="email" name="name" value="" placeholder="e-mail"/>
                </div>
            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="phone icon"></i>
                    <input id="" type="number" name="name" value="" placeholder="Telefon"/>
                </div>
            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="pin icon"></i>
                    <input id="" type="text" name="name" value="" placeholder="Adresa"/>
                </div>
            </div>
            <button type="submit" value="Spremi" class="ui fluid large submit button">Naruči</button>
        </div>
    </form>
    <div>
