<?php var_dump($this->listings);?>
<?php var_dump($this->qty);exit;?>

<h1>My Order</h1>
<table class="ui celled padded table">
    <thead>
    <tr><th class="single line">Slika proizvoda</th>
        <th>Naziv proizvoda</th>
        <th>Opis</th>
        <th>Količina</th>
        <th>Uredi</th>
    </tr></thead>
    <tbody>
    <tr>
        <td>
            <h2 class="ui center aligned header">
                <img src="http://placehold.it/100x100" alt="">
            </h2>
        </td>
        <td class="single line">
            Naziv proizvoda
        </td>
        <td>
            Creatine is the reference compound for power improvement, with numbers from one meta-analysis to assess potency
        </td>
        <td class="right aligned">
            3
        </td>
        <td>x</td>
    </tr>
    </tbody>
</table>

<div class="ui large form" _lpchecked="1">
    <form method="post" action="/account/edit">
        <div class="ui stacked segment">
            <div class="field">
                <div class="ui left icon input">
                    <i class="user icon"></i>
                    <input id="" type="text" name="name" value="" placeholder="Ime i Prezime"/>
                </div>

            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="mail icon"></i>
                    <input id="" type="email" name="name" value="" placeholder="e-mail"/>
                </div>
            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="phone icon"></i>
                    <input id="" type="number" name="name" value="" placeholder="Telefon"/>
                </div>
            </div>
            <div class="field">
                <div class="ui left icon input">
                    <i class="pin icon"></i>
                    <input id="" type="text" name="name" value="" placeholder="Adresa"/>
                </div>
            </div>
            
            </div>
    </form>
<div>

